---
- name: Converge
  hosts: all
  collections:
    - {{ cookiecutter.namespace_slug }}.{{ cookiecutter.collection_slug }}
  tasks:
    - name: Run collection smoke test
      ansible.builtin.debug:
        msg: "Collection {{ cookiecutter.namespace_slug }}.{{ cookiecutter.collection_slug }} loaded successfully"
