---
- name: Verify
  hosts: all
  tasks:
    - name: Verify collection loaded successfully
      ansible.builtin.assert:
        that:
          - true
        fail_msg: "Add collection verification tasks here"
